export const FATCH_MEDICINE = "FATCH_MEDICINE";
export const ERROR_MEDICINE = "ERROR_MEDICINE";
export const LODING_MEDICINE = "LODING_MEDICINE"

export const ADD_SIGNUP = "ADD_SIGNUP";

export const SIGNUP_AUTH = "SIGNUP_AUTH";
export const LOGIN_AUTH = "LOGIN_AUTH";
export const GOOGLE_AUTH = "GOOGLE_AUTH";